### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by kyrnbs** [volodymyrsmirnov/yadisk-link-extractor#2]
Traceback (most recent call last):
  File "yadisk-extract.py", line 75, in <module>
    print url, ">", get_direct_url(url)
  File "yadisk-extract.py", line 26, in get_direct_url
    raise YandexDiskException("Something went wrong during pass.yandex.ru request")
**main**.YandexDiskException: Something went wrong during pass.yandex.ru request

**Comment by tuntapovski** [comment]
i get same error, script must be updated
yandex changed its codes probably
